### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by tonycpp** [tonycpp/goRent#4]
search bar
filter button

map 

car cards
icons bar

![image](https://user-images.githubusercontent.com/41452233/95642925-310e9e80-0a82-11eb-840a-6afcf819ce97.png)

1 Celeste Claro: #AAD2DA
2 Blanco: #FAFBFB
3 Gris Oscuro: #3B4146
4 Celeste: 74BDC9
5 Negro : #0C0E0F
6 Gris Claro: #A2AFB2
7 Naranja: #F35124

![image](https://user-images.githubusercontent.com/41452233/95643984-7f736b80-0a89-11eb-9bfc-ef22e1acfff0.png)

Font - Material App
`final theme = ThemeData(
  fontFamily: 'Poppins',
);
`

yaml file
```
fonts:
     - family: Mulish
       fonts:
         - asset: fonts/Mulish-Italic-VariableFont_wght.ttf
 
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf``
```
